require 'plugins'
require 'plugins/configs/autopair'
require 'plugins/configs/autotag'
require 'plugins/configs/bufferline'
require 'plugins/configs/cmp'
require 'plugins/configs/comment'
require 'plugins/configs/lualine'
require 'plugins/configs/mdeval'
require 'plugins/configs/metals'
require 'plugins/configs/nvimtree'
require 'plugins/configs/symbols'
require 'plugins/configs/surround'
require 'plugins/configs/treesitter'
require 'plugins/configs/toggleterm'
require 'plugins/configs/window'

require 'plugins/lsp'

require 'configs'
require 'configs/mappings'
require 'configs/colors'
require 'configs/utils'
